# Generated by Django 4.2.20 on 2025-04-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work')),
                ('camera', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('login_require', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('album', models.ManyToManyField(to='work.album')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
